# See   https://kubernetes.io/docs/api-reference/v1.6/
#       https://kubernetes.io/docs/api-reference/v1.6/#deployment-v1beta1-apps
#

# webapi app
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    product: k8s-demo
  name: webapi
spec:
  replicas: 1
  # This slows things down so we can see changes taking place via the curl loop
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: webapi
        product: k8s-demo
    spec:
      containers:
      - name: webapi
        image: pmcgrath/webapi:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /environment
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
          - name: webapi-config
            # Waiting on https://github.com/kubernetes/kubernetes/issues/44815 so we can get appsettings file in the /app directory
            mountPath: /app/config
            readOnly: true
      volumes:
        - name: webapi-config
          configMap:
            name: webapi
            items:
              - key: appsettings.json
                path: appsettings.json
